### ISSUE TITLE
Clear the cached data

### ISSUE THREAD

**Issue by hick209** [VictorAlbertos/RxCache#10]
There should be a way to clear all the cached data, from both disk and memory (with one single call).
For example, imagine a scenario where you have a user logged in with all his information cached either in disk and memory.
This user logs out an another user logs in in the same device, there might be some displayed information that actually belongs to the first user.

Of course you could evit every single cache entry you have, but this is very labourous. What if you have 20K individual cache entries?
So that's where a clearAll() method would come in handy.

**Comment by VictorAlbertos** [comment]
Hi @hick209 

I don’t think you need that. You should let RxCache take cares of this by its own, with the proper endpoints configuration. That’s the hole point, indeed, configuring endpoints always thinking in the long term.  

If you have several endpoint, whose data depends on the current user, you should use DynamicKey for all these endpoints, passing the user id as the key. And set a proper LifeCache time in order to be evicted when RxCache thinks it is needed to free some space in disk.  

That way, when a new user is logged, you will be playing only with the proper data, and the old one will be automatically evicted at some point.

But if you really really really want to do that, you can always list the files of the filesystem whose path you supplied when you built the RxCache instance.

```java
File[] files =  application.getFilesDir().listFiles();
for (File file: files) {
    file.delete();
}
```
