### ISSUE TITLE
Providers return reference to objects but instead they should return copy of objects to preserve immutability

### ISSUE THREAD

**Issue by miguelbcr** [VictorAlbertos/RxCache#13]
When I call to a provider and I retrieve an object from the cache (it can be a simple object, a list, ...) and I modify it, for instance, remove an item from the list, modify the object's properties, then the next time when I call to that provider, the provided object from the cache is the same object I've modified in my app.

So, I think the right behaviour should be that the providers return copy to objects, instead of return reference to objects. This way RxCache will be able to preserve immutability and stay sync with the persistence layer.

**Comment by VictorAlbertos** [comment]
Yes. 

We need to fix this. RxCache must return a copy instead of a reference object. 

We can add a new method annotation, @ByReference, using it RxCache will keep returning references instead of copies.  The problem with this approach is that the persistence layer won't be able to reflect these changes, event thought the memory layer will do. That's why I think it is better to not create this new @annotation and just fix the problem, even thought it will involve changing the current behaviour without giving a change to RxCache to behaves in the old fashion way.

**Comment by euskode** [comment]
@VictorAlbertos this does mean that the project can only be used as a cache layer for reads, doesn't it? 

Perhaps this is in keeping with the project's original design philosophy, however, I had been hoping to use RxCache both as a read layer on top of Retrofit, as well as a local caching facility for changes made to entities on the device. One such example would be if mutations are made to an entity (think expensive, long-running async actions) which the device in turn hears back from the server via WebSocket (instead of polling). When these messages arrive, one would think that they can be applied to the reference returned by RxCache (and that there'd be an additional method to trigger persistence), but with a deep copy, this would never be able to happen.

I'd love to get your thoughts on whether this is a use case that the project intends to support in some way.

**Comment by VictorAlbertos** [comment]
Hi @euskode.

You are right about the fact that RxCache would be much powerful working with reference objects, instead of copies. The problem is the persistence layer. How to keep it sync with the memory layer? RxCache api its characterised by trying to be not api at all. The java plain interface that you supply as the cache providers is exactly what you get after building it with RxCache class. 

It’s true -although not documented in the docs, that you can wrap the generic type observable inside a [Reply](https://github.com/VictorAlbertos/RxCache/blob/master/rx_cache/src/main/java/io/rx_cache/Reply.java ) object. It was created for testing purposes, [here](https://github.com/VictorAlbertos/RxCache/blob/master/rx_cache/src/test/java/io/rx_cache/internal/ProvidersRxCache.java) you can check that the response of many method wrappers the data inside the Reply class.

This Reply class could have a method called something like `syncPersistence()`, that way after making some change to the data, you can call it to sync it with the persistence layer. I need to think more carefully about the internals details, but I think it could be possible to do it. But I'm not sure if this is the way to go. What do you think?

Nevertheless I use RxCache a lot. xD Not only as a reading cache. 

```java
//The provider must be populated before.

Observable<Void> updateUser(User user) {
	Observable<List<User>> oCachedUsers = rxProviders.getUsers(Observable.just(null), new EvictProvider(false));

	Observable<List<User>> oUsersUpdated = oCachedUsers.flatMapIterable(users -> users)
	     .map(candidate -> {
                    if (candidate.getId() == user.getId()) // do some changes
              })
	     .toList()

	return rxProviders.getUsers(oUsersUpdated, new EvictProvider(true));
}

```

RxCache is pretty "writable", indeed ;) Give it a try, and let me know how do you feel about using this approach.

**Comment by euskode** [comment]
Yeah, I'm actually using `Observable<Reply<MyEntity>` already, so your suggestion makes perfect sense. Frankly, it would be awesome if persistence was handled this way :smile: 

As for your current approach, I totally get that what you are showcasing is indeed possible, but when coupled with `retrofit`, your `return` line will hit the server again, which is rather clunky, or am I missing something?

Finally, somewhat on this topic, how would deletions be handled? For instance, say that a silent GCM notification or WebSocket message comes in telling us that an entity is no longer good and must thus be discarded from the app's working data bundle. The way I understand it, calling into the provider and forcing a `retrofit` refetch would be the only way to accomplish this, isn't it?

**Comment by VictorAlbertos** [comment]
Nope. We are only working with previous cached data. I think the next example answer your questions :)

```java

public class Repository {
	private final RxProviders rxProviders; //RxCache
	private final Api api; //Retrofit

	@Inject public Repository(RxProviders rxProviders, Api api) {
		this.rxProviders = rxProviders;
		this.api = api;
	}

	Observable<List<User>> getUsers(boolean refresh) {
		return rxProviders.getUsers(api.getUsers, new EvictProvider(refresh));
	}

	Observable<Void> updateUser(User user) {
		//Here we are not hitting the api at all. We are working with cached data only.

		Observable<List<User>> oCachedUsers = rxProviders.getUsers(Observable.just(null), new EvictProvider(false));

		Observable<List<User>> oUsersUpdated = oCachedUsers.flatMapIterable(users -> users)
		     .map(candidate -> {
	                    if (candidate.getId() == user.getId()) // do some changes
	              })
		     .toList();

		return rxProviders.getUsers(oUsersUpdated, new EvictProvider(true))
				.map(users -> Observable.just(null));
	}

	Observable<Void> deleteUser(User user) {
		//Again, we are only working with cached data.

		Observable<List<User>> oCachedUsers = rxProviders.getUsers(Observable.just(null), new EvictProvider(false));

		Observable<List<User>> oUsersUpdated = oCachedUsers.flatMapIterable(users -> users)
		     .filter(candidate -> candidate.getId() == user.getId())
		     .toList();

		return rxProviders.getUsers(oUsersUpdated, new EvictProvider(true))
				.map(users -> Observable.just(null));
	}
}

//usage

boolean pullToRefresh = ??

repository.getUsers(pullToRefresh).subscribe(users -> {
	User user = users.get(0);
	user.setName("updatedName");

	repository.updateUser(user).subscribe(nothing -> {
		//now the user is updated. we are happy :)
	})
});

user = //retrieved from a gcm notificaion
repository.deleteUser(user).subscribe(nothing -> {
	//now the user is deleted. we are happy :)
})

```

**Comment by euskode** [comment]
I see I see, yeah, I have not tested it yet but that does look like it would work! Further, it removes the need for a persistence sync method as far as I can tell.

Thank you kindly for your explanations and code here, that was super helpful. I think a lot of folks would appreciate it if the update and delete cases made it to the `README` too, as the current contents make it seem like the project is designed for read-only operation, which it clearly is not :laughing:

**Comment by VictorAlbertos** [comment]
I'll do that ;) 

Thanks to you for point out these questions. As you said, maybe some users think that RxCache can't work "writing" data, and that's need to be fixed.

**Comment by VictorAlbertos** [comment]
Hi @euskode :)

I've just created a new actionable api to perform write operations in a more easy way. You can check the section 'Actionable API RxCache' of the readme document.

I hope you will find useful.

**Comment by euskode** [comment]
Oh yes, you're too good, can't wait to check this out soon!
