### ISSUE TITLE
RxCache Shouldn't Be External

### ISSUE THREAD

**Issue by SeanCode** [VictorAlbertos/RxCache#18]
the RxCache class is the entry of whole cache system, why make it internal?

**Comment by VictorAlbertos** [comment]
Hi @SeanCode 

[RxCache](https://github.com/VictorAlbertos/RxCache/blob/master/rx_cache/src/main/java/io/rx_cache/internal/RxCache.java) class is not *internal*. In fact, there is not such visibility scope for a `class` in Java :)

`RxCache` class is a `public` `class` but it is located in a `package` which name is 'internal'. Here is where most of the 'internal' code is located indeed. And because of that, most classes has package visibility. So they can't be access outside the package. 

Now, because of its scope visibility, I have no other choice but to put `RxCache` inside this package, in order to be able to access all these classes with package visibility. 

Long time ago I [asked on stack](http://stackoverflow.com/questions/28765082/visibility-scope-project-module) if there was an 'internal' modifier  -just like the [internal](https://developer.apple.com/swift/blog/?id=5) one of `swift`, which could protect its clases/methods from the outside world but keeping them visible for the entire project/module. But, obviously, there wasn't such modifier :)

**Comment by VictorAlbertos** [comment]
I'm going to close the issue. If you have more questions please reopen it.
