### ISSUE TITLE
Survive Android configuration changes

### ISSUE THREAD

**Issue by rafakob** [VictorAlbertos/RxCache#21]
Hello,
I'm just starting playing around with RxCache. Can it handle somehow configuration changes? What I mean by that is a typical use case:
1) User starts an expensive network call.
2) User rotates screen - request is still running in the background.
3) After activity recreation it subscribes to ongoing call.

I've done some simple tests and it looks like on activity recreation the call is being reset.

**Comment by VictorAlbertos** [comment]
RxCache knows nothing about Android. It's a cache system for java applications, not only for Android apps. 

So, I suggest to you to take a look at this library, [RxLifeCycle](https://github.com/trello/RxLifecycle), which is very handy to sync observable subscriber with android life cycle. 

I'm going to close the issue because I think it is not related with RxCache, but feel free to reopen it at any moment for further clarifications.
