### ISSUE TITLE
@LifeCache(duration = 0, timeUnit = TimeUnit.MINUTES)

### ISSUE THREAD

**Issue by kraghu** [VictorAlbertos/RxCache#33]
what happens when I provide @LifeCache(duration = 0, timeUnit = TimeUnit.MINUTES) ? It seems like it is caching for ever ?

**Comment by VictorAlbertos** [comment]
Yep. 

Is there some real implication beyond that testing the internals of RxCache? I mean, are you getting a hard time because of that? :)

[Here](https://github.com/VictorAlbertos/RxCache/blob/master/core/src/main/java/io/rx_cache/internal/ProxyTranslator.java#L78) and [here](https://github.com/VictorAlbertos/RxCache/blob/master/core/src/main/java/io/rx_cache/internal/cache/RetrieveRecord.java#L36) you can see why this happens.

**Comment by kraghu** [comment]
It took a while to guess the culprit as I was hoping it would not make a call with the cache turned off if I call it with zero. That way I could use the same pattern for my non cached retrofit network call.

**Comment by VictorAlbertos** [comment]
Ok, so you had a hard time with this xD

Let me see if I can fix it today.

**Comment by kraghu** [comment]
Thanks :)

-me

On May 29, 2016, at 1:01 AM, Víctor Albertos <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, so you had a hard time with this xD

Let me see if I can fix it today.

**Comment by VictorAlbertos** [comment]
Done!

Try the new version please:

 `compile "com.github.VictorAlbertos.RxCache:core:1.4.7"`

**Comment by kraghu** [comment]
Will look into it on Monday as I am getting a library conflict with the simple new version. I was using 1.4.2 . 
Error:Conflict with dependency 'com.google.guava:guava'. Resolved versions for app (18.0) and test app (19.0-rc2) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by VictorAlbertos** [comment]
RxCache doesn't use guava since [1.4.0 version](https://github.com/VictorAlbertos/RxCache/releases/tag/1.4.0).

I think this is something to do with your own application.

**Comment by kraghu** [comment]
am checking it .

**Comment by VictorAlbertos** [comment]
Great ;)
