### ISSUE TITLE
Example Persistence mechanism using sqlite/Orm

### ISSUE THREAD

**Issue by pratamawijaya** [VictorAlbertos/RxCache#5]
any sample for how to implement custom persistence mechanism using sqlite/orm or Realm ?

**Comment by VictorAlbertos** [comment]
There is no example about how to implement another persistence mechanism because it is not a feature of RxCache.

But RxCache offers this possibility by accepting a custom implementation of Persistence interface, as it is documented in the [README file](https://github.com/VictorAlbertos/RxCache/blob/master/README.md). 

```java
new RxCache.Builder()
            .persistence(new Persistence() {
                @Override public void saveRecord(String key, Record record) {
                    
                }

                @Override public void delete(String key) {

                }

                @Override public <T> Record<T> retrieveRecord(String key) {
                    return null;
                }
            })
            .using(Providers.class);
```

Personally, I would not use sqlite, because it defeats the whole purpose of keeping things simple. Obviously, maybe your application has some requirements which force you to create and maintain a database. But in the end your application is a client-application, which means at first glance not need to keep track of a large amount of data. 

Anyway, if you finally end up implementing your own Persistence layer, please let me know how it was.
