### ISSUE TITLE
get throwable error from source

### ISSUE THREAD

**Issue by pratamawijaya** [VictorAlbertos/RxCache#50]
Hi, i want to catch my throwable error from retrofit, but from rxcache just return something like these
![image](https://cloud.githubusercontent.com/assets/2455823/16539111/0491fb88-4063-11e6-8efe-8bbc0dd9e81f.png)

**Comment by VictorAlbertos** [comment]
Take a look to the throwable instance. It should be a composite error, where, as long as the error thrown by RxCache, it should be present the error thrown by Retrofit.

Anyway, this happens when your source loader (or for this matter the observable returned by retrofit) returns a null value or throws an error. If you don't find the composite error, try to find the original error subscribing to Retrofit without using RxCache.

**Comment by VictorAlbertos** [comment]
Closing due to lack of feedback.
