### ISSUE TITLE
Support for rx.Single

### ISSUE THREAD

**Issue by PaulWoitaschek** [VictorAlbertos/RxCache#60]
Title says it. It would be great to have support for singles (as all my api calls are Singles).

**Comment by VictorAlbertos** [comment]
We'll leave the issue open to see if more people are interested on it. It implies several changes for both branches 1.x and 2.x, and because I want to expose the same functionality from ReactiveCache library, I would need to change it too in order to support Single (again, for both branches).

In any case, we should wait until 2.x ships a stable version, because I'm not planning to support 1.x indefinitely.

**Comment by PaulWoitaschek** [comment]
If I understand RxCache correctly, it will always emit a single item.
So Single is the correct abstraction for this. Observable implies that there could be more than 1 item.

**Comment by VictorAlbertos** [comment]
You're right, conceptually `Single` would be the right reactive type for RxCache. The problem is that if you take a look to any Retrofit tutorial (even the official page) you are going to see `Observable` as the standard type. So, this type is far more popular than `Single`, that's why `Observable` is the main type for RxCache too.

That said, RxCache will support `Single` eventually, but right now it's not a good moment for the reason I've already explained to you.
