### ISSUE TITLE
RxCache dependency returns an apk archive

### ISSUE THREAD

**Issue by AmandaRiu** [VictorAlbertos/RxCache#7]
Hi Victor, 

First let me say, thank you for sharing this library. I'm still just exploring, but so far it looks really cool. 

I downloaded your sample project for android and configured it in Android Studio. Just a quick note that I had to change the double-quotes for calling your dependency in sample_date.build.gradle to single quotes or it wouldn't compile:

`compile ('com.github.VictorAlbertos.RxCache:android:0.4.9') {
        exclude module: 'guava'
 }`

Not a big deal at all, maybe that works fine in some environements...it just wouldn't work in mine. 

The big issue I'm having right now is that the call for this dependency returns an APK instead of an AAR so I'm getting this error:

`Warning:Dependency com.github.VictorAlbertos.RxCache:android:0.4.9 on project sample_android resolves to an APK archive which is not supported as a compilation dependency. File: /Users/foo/.gradle/caches/modules-2/files-2.1/com.github.VictorAlbertos.RxCache/android/0.4.9/a29a405c4d3c542571e9f062b7158916fecb2219/android-0.4.9.apk`

Thanks,
Amanda

**Comment by VictorAlbertos** [comment]
Hi Amanda. 

Thanks to you for using it!

That’s really weird. Both of two errors. 

About the first one, I did not see something like that. Never xD 

About the second one, it is really weird too. Because the library RxCache itself is a java module -nothing to do with Android, the same goes for "sample_data" module, which is a dependency to "sample_android" android module.

Have you changed any build.grade file from any module? It seems like if you were adding the android application module “sample_android” to another android application module. This error happens when an android module application is added to another android module application, the first one should be an android library module, instead of an android application module.
